### ISSUE TITLE
TODO in November

### ISSUE THREAD

**Issue by aquarhead** [aquarhead/aquarhead.github.io#2]
- [x] Translate ETS chapter for elixir-school
- [ ] ~~Killmail checker using GenStage~~
- [x] GitHub Project columns to GitHub Issue labels service
- [x] Introducing ExLogLite
- [x] Learn Elm
- [x] Learn GraphQL
- [x] https://github.com/aquarhead/mashiro_no_asobiba/issues/1
- [x] https://github.com/ElaWorkshop/one-clock/projects/1

**Comment by aquarhead** [comment]
https://github.com/doomspork/elixir-school/pull/783

**Comment by aquarhead** [comment]
https://github.com/aquarhead/card_labeler

**Comment by xhacker** [comment]
:mb:

**Comment by aquarhead** [comment]
https://www.youtube.com/watch?v=wPPFhcqGcvk

**Comment by aquarhead** [comment]
Guess I don't have time for the GenStage stuff.
